export const POSTS = [
  {
    slug: "hvornaar-skal-du-outsource-bogforing",
    title: "Hvornår skal du outsource din bogføring?",
    description: "De fleste selvstændige starter med selv at bogføre. Her er de tegn, der typisk viser, at det er tid til at få hjælp - og hvad det kan spare dig for.",
    category: "Bogføring & regnskab",
    categorySlug: "bogforing-regnskab",
    publishedAt: "2026-08-12",
    content: [
      { type: "p", text: "De fleste, der starter for sig selv, bogfører selv i begyndelsen. Det er billigt, og når der kun er få bilag om måneden, er det til at overskue. Men på et tidspunkt vender billedet - og det sker ofte tidligere, end man selv opdager." },
      { type: "h2", text: "Tegn på at det er tid til at få hjælp" },
      { type: "list", items: [
        "Du udskyder bogføringen til sidst på måneden - eller kvartalet",
        "Du er usikker på, om du har husket alle fradrag",
        "Momsindberetningen tager flere timer, hver gang den skal laves",
        "Du bruger aftener og weekender på regnskab, i stedet for på selve forretningen",
        "Din revisor beder ofte om afklaringer, fordi bogføringen er uklar",
      ]},
      { type: "p", text: "Hvis bare to eller tre af de her punkter lyder bekendt, er det sandsynligvis ikke tiden i sig selv, der er problemet - det er, at bogføring kræver en anden form for fokus, end resten af dagen gør." },
      { type: "h2", text: "Hvad koster det at få hjælp?" },
      { type: "p", text: "Prisen afhænger naturligvis af, hvor meget bogføring der reelt er, og hvor rodet den er i forvejen. En løbende, ordnet bogføring for en mindre enkeltmandsvirksomhed koster typisk markant mindre end en oprydning i et helt års rod - så jo tidligere man får sat en fast rutine op, jo billigere er det som regel at holde ved." },
      { type: "h2", text: "Selv en enkelt opgave kan være nok" },
      { type: "p", text: "Man behøver ikke vælge mellem at gøre det hele selv eller hyre en fast bogholder på månedsbasis. Mange starter i stedet med en enkeltstående opgave - få ryddet op i et kvartal, få lavet momsindberetningen for denne gang, eller få et andet sæt øjne på årsregnskabet, før det sendes videre." },
    ],
  },
  {
    slug: "vaelg-den-rigtige-oversaetter",
    title: "Sådan vælger du den rigtige oversætter til din virksomhed",
    description: "En dårlig oversættelse kan koste mere end den sparer. Her er, hvad du bør kigge efter, når du skal have oversat tekst til din virksomhed.",
    category: "Oversættelse",
    categorySlug: "oversaettelse",
    publishedAt: "2026-08-15",
    content: [
      { type: "p", text: "En oversættelse handler ikke kun om at skifte ordene ud - det handler om, at teksten stadig lyder rigtig, når den er færdig. Det er især tydeligt, når det går galt: en produktbeskrivelse, der lyder maskinoversat, eller en kontrakt, hvor et enkelt forkert ord ændrer betydningen." },
      { type: "h2", text: "Hvad skal du kigge efter?" },
      { type: "list", items: [
        "Er personen modersmålstalende på målsproget, ikke bare flydende?",
        "Har vedkommende erfaring med netop din type tekst (juridisk, teknisk, markedsføring)?",
        "Kan de vise eksempler på tidligere arbejde?",
        "Forstår de konteksten - hvem skal læse teksten, og hvorfor?",
      ]},
      { type: "h2", text: "Maskinoversættelse som udgangspunkt - ikke facit" },
      { type: "p", text: "Værktøjer som Google Translate og AI-baserede oversættere er blevet markant bedre, men de rammer stadig ved siden af nuancer, tonefald og branchespecifikke udtryk. For korte, uformelle beskeder er det ofte fint. For alt, der repræsenterer virksomheden udadtil - hjemmesider, kontrakter, markedsføring - er et menneskeligt gennemsyn stadig det, der adskiller professionelt fra 'det virker nok'." },
      { type: "h2", text: "Start med den vigtigste tekst først" },
      { type: "p", text: "Har du mange sider, der skal oversættes, behøver du ikke gøre det hele på én gang. Start med den tekst, flest besøgende rent faktisk ser - typisk forsiden og de vigtigste produktsider - og byg videre derfra." },
    ],
  },
  {
    slug: "tegn-paa-behov-for-kundeservice-hjaelp",
    title: "5 tegn på at din virksomhed har brug for ekstra kundeservice-hjælp",
    description: "Kundeservice er ofte det første, der lider, når en virksomhed vokser. Her er de typiske advarselstegn, og hvordan man løser det uden at ansætte fast.",
    category: "Kundeservice & support",
    categorySlug: "kundeservice-support",
    publishedAt: "2026-08-19",
    content: [
      { type: "p", text: "Kundeservice er sjældent det, man tænker på først, når en virksomhed vokser - men det er ofte det første, kunderne mærker, hvis det halter. Her er nogle af de typiske tegn på, at det er ved at blive et problem." },
      { type: "h2", text: "1. Svartiden stiger" },
      { type: "p", text: "Går der flere dage, før en kunde får svar på en simpel henvendelse, mister I ikke bare den ene kunde - I mister den anonyme anbefaling, kunden ellers ville have givet." },
      { type: "h2", text: "2. Ferier og sygdom skaber huller" },
      { type: "p", text: "Hvis kundeservice ligger på én persons skuldre, stopper den, når den person er væk. Det er sårbart, og det er ofte her, virksomheder først opdager, hvor afhængige de er blevet." },
      { type: "h2", text: "3. Samme spørgsmål stilles igen og igen" },
      { type: "p", text: "Går der meget tid med at svare det samme igen og igen, er det ofte tegn på, at der mangler en FAQ eller et fast svar-katalog - noget en ekstern hjælper hurtigt kan sætte op." },
      { type: "h2", text: "4. Reklamationer bliver hængende" },
      { type: "p", text: "En reklamation, der ikke bliver håndteret hurtigt, vokser sig ofte større, end den behøvede at være." },
      { type: "h2", text: "5. I overvejer en fastansættelse, men er ikke helt sikre endnu" },
      { type: "p", text: "Det er her, en løsere løsning ofte giver mest mening - få hjælp til at dække spidsbelastninger eller enkelte perioder, uden at binde jer til en fast ansættelse, før I ved, om behovet er permanent." },
    ],
  },
  {
    slug: "brug-ai-i-hverdagen-uden-at-spilde-tid",
    title: "Sådan bruger du AI i din hverdag - uden at spilde tid på det",
    description: "AI-værktøjer kan spare timer om ugen, men kun hvis de bruges rigtigt. Her er en ærlig gennemgang af, hvor det giver mening - og hvor det ikke gør.",
    category: "AI-opgaver",
    categorySlug: "ai-opgaver",
    publishedAt: "2026-08-22",
    content: [
      { type: "p", text: "Der er meget hype om AI lige nu, og en del af det er berettiget - men langt fra alt. Her er en ærlig gennemgang af, hvor AI-værktøjer som ChatGPT og lignende faktisk sparer tid i en travl hverdag, og hvor de mest skaber ekstra arbejde." },
      { type: "h2", text: "Hvor det virker godt" },
      { type: "list", items: [
        "Førsteudkast til tekster - mails, opslag, produktbeskrivelser",
        "Opsummering af lange dokumenter eller møder",
        "Automatisering af tilbagevendende, forudsigelige opgaver",
        "Idégenerering, når man er gået i stå",
      ]},
      { type: "h2", text: "Hvor det kræver mere end det lover" },
      { type: "p", text: "AI er ikke god til at kende fakta, den ikke har set før - den gætter i stedet for at sige 'det ved jeg ikke'. Alt, der skal være faktuelt korrekt (tal, navne, juridiske detaljer), bør derfor altid tjekkes af et menneske bagefter." },
      { type: "h2", text: "Den største tidsbesparelse ligger i opsætningen" },
      { type: "p", text: "De fleste, der 'ikke får noget ud af AI', har typisk bare ikke sat det rigtigt op til deres egen arbejdsgang endnu. Den tid, det tager at lære at skrive gode prompts eller sætte en automatisering korrekt op første gang, betaler sig ofte hurtigt tilbage - men det kræver, at nogen bruger tiden på det én gang." },
    ],
  },
  {
    slug: "hvad-koster-det-at-faa-lavet-en-hjemmeside",
    title: "Hvad koster det at få lavet en hjemmeside?",
    description: "Prisen på en hjemmeside spænder enormt. Her er, hvad der reelt påvirker prisen, og hvordan du undgår at betale for meget - eller for lidt.",
    category: "Hjemmeside & IT",
    categorySlug: "hjemmeside-it",
    publishedAt: "2026-08-26",
    content: [
      { type: "p", text: "Spørger man rundt, får man svar, der spænder fra et par tusind kroner til flere hundredtusinde. Det er ikke fordi, nogen lyver - det er fordi, 'en hjemmeside' dækker over meget forskellige ting." },
      { type: "h2", text: "Det, der reelt påvirker prisen" },
      { type: "list", items: [
        "Om det er en simpel præsentationsside eller en webshop med betaling",
        "Om designet skal være unikt, eller om en skabelon er nok",
        "Hvor mange undersider og hvor meget indhold, der skal skrives",
        "Om der skal integreres med andre systemer (bogføring, CRM, lager)",
        "Om det bygges i et system som WordPress, eller kodes fra bunden",
      ]},
      { type: "h2", text: "Undgå at betale for meget" },
      { type: "p", text: "Den mest almindelige fejl er at betale for funktioner, man reelt ikke får brug for det første år - avancerede integrationer, skræddersyet design til hver eneste underside, eller et system, der er bygget til en langt større virksomhed, end man selv er. Det er sjældent en dårlig idé at starte enklere, end man tror, man har brug for." },
      { type: "h2", text: "Glem ikke driften bagefter" },
      { type: "p", text: "Selve opsætningen er kun første del af regningen. Hosting, opdateringer, og løbende rettelser er en tilbagevendende udgift, som er værd at spørge ind til, før man går i gang - ikke bagefter." },
    ],
  },
  {
    slug: "skriv-en-jobannonce-der-virker",
    title: "Sådan skriver du en jobannonce, der rent faktisk virker",
    description: "De fleste jobannoncer læses i under 20 sekunder. Her er, hvad der får de rigtige ansøgere til at stoppe op - og hvad der får dem til at klikke videre.",
    category: "Tekstforfatning & korrektur",
    categorySlug: "tekstforfatning-korrektur",
    publishedAt: "2026-08-29",
    content: [
      { type: "p", text: "En jobannonce har typisk et par sekunder til at fange opmærksomheden, før en potentiel ansøger klikker videre til den næste. Alligevel bliver de fleste stillingsopslag skrevet, som om ansøgeren allerede har besluttet sig for at læse hele annoncen grundigt." },
      { type: "h2", text: "Start med det, der reelt betyder noget for ansøgeren" },
      { type: "p", text: "De fleste annoncer starter med en lang beskrivelse af virksomheden. Den kommer bedre længere nede - de første linjer bør handle om selve jobbet, hvad man reelt skal lave, og hvad man får ud af det." },
      { type: "h2", text: "Vær konkret, ikke bare positiv" },
      { type: "p", text: "'Et spændende job i en dynamisk virksomhed' siger reelt ingenting. Hvad laver man en tirsdag formiddag? Hvem sidder man sammen med? Det er den slags konkrete detaljer, der får folk til at kunne forestille sig sig selv i rollen." },
      { type: "h2", text: "Lange kravlister skræmmer flere væk, end de tiltrækker" },
      { type: "p", text: "Undersøgelser peger på, at særligt kvindelige ansøgere er tilbøjelige til slet ikke at søge, hvis de ikke opfylder samtlige krav på en liste - selvom de fleste krav reelt er 'kan være rart at have', ikke 'skal have'. Overvej at skille de to typer krav tydeligt ad." },
    ],
  },
  {
    slug: "derfor-boer-du-faa-et-ekstra-oeje-paa-kontrakter",
    title: "Derfor bør du få et ekstra øje på dine kontrakter",
    description: "De fleste kontraktproblemer opdages først, når det er for sent. Her er, hvorfor et ekstra gennemsyn ofte er billigere end konsekvensen af at springe det over.",
    category: "Kontraktgennemgang",
    categorySlug: "kontraktgennemgang",
    publishedAt: "2026-09-01",
    content: [
      { type: "p", text: "De fleste læser en kontrakt igennem, før de skriver under - men 'læse igennem' og 'forstå fuldt ud, hvad man skriver under på' er ikke altid det samme. Kontraktsprog er lavet til at være præcist, ikke til at være letlæst." },
      { type: "h2", text: "De klausuler, der oftest overses" },
      { type: "list", items: [
        "Opsigelsesvarsler og bindingsperioder",
        "Ansvarsbegrænsninger - hvem hæfter for hvad, hvis noget går galt",
        "Automatisk fornyelse, hvis man ikke aktivt siger fra i tide",
        "Konkurrenceklausuler, der rækker længere, end man tror",
      ]},
      { type: "h2", text: "Et ekstra øje koster mindre end en tvist" },
      { type: "p", text: "Sammenlignet med, hvad det koster at ende i en reel uenighed om en kontrakt senere, er prisen for at få den gennemgået grundigt på forhånd typisk beskeden. Det gælder både lejekontrakter, samarbejdsaftaler og ansættelseskontrakter." },
      { type: "h2", text: "Det behøver ikke være en advokat hver gang" },
      { type: "p", text: "Ikke alle kontrakter kræver en fuld juridisk gennemgang til advokatpriser. For mange almindelige aftaler er det nok at få et grundigt, kyndigt gennemsyn - der specifikt kan pege på det, der er værd at få afklaret, før man skriver under." },
    ],
  },
  {
    slug: "styr-paa-dataindtastning-uden-at-drukne",
    title: "Sådan får du styr på dataindtastning uden at drukne i det",
    description: "Dataindtastning lyder simpelt, men æder ofte langt mere tid, end man forventer. Her er, hvordan man griber det an mest effektivt.",
    category: "Dataindtastning",
    categorySlug: "dataindtastning",
    publishedAt: "2026-09-04",
    content: [
      { type: "p", text: "Dataindtastning er en af de opgaver, der ser små ud i planlægningen, men som konsekvent tager længere tid, end man regner med. Et regneark med 500 rækker lyder overskueligt - indtil man rent faktisk sidder med det." },
      { type: "h2", text: "Hvorfor det tager længere tid, end man tror" },
      { type: "p", text: "Det er sjældent selve indtastningen, der er langsom - det er de mange små beslutninger undervejs: er dette navn stavet forkert, eller er det bare usædvanligt? Skal dette felt stå tomt, eller mangler der data? Den slags mikro-stop lægger sig oveni hinanden." },
      { type: "h2", text: "Ryd op, før du fylder på" },
      { type: "p", text: "Har du en eksisterende, rodet datamængde, betaler det sig næsten altid at få den ryddet op og struktureret, før nye data tilføjes ovenpå - ellers arver man de samme fejl igen og igen." },
      { type: "h2", text: "Overvej hvad der reelt skal gøres manuelt" },
      { type: "p", text: "En del dataindtastning kan i dag automatiseres helt eller delvist. Men før man automatiserer, skal dataene ofte være rene og konsistente først - og den oprydning er stadig typisk et manuelt arbejde, i hvert fald første gang." },
    ],
  },
];

export function getPostBySlug(slug) {
  return POSTS.find((p) => p.slug === slug) || null;
}
