export const CATS = [
  { name: "Bogføring & regnskab", icon: "Calculator" },
  { name: "Kundeservice & support", icon: "Headphones" },
  { name: "Dataindtastning", icon: "Keyboard" },
  { name: "Oversættelse", icon: "Languages" },
  { name: "Tekstforfatning & korrektur", icon: "PenTool" },
  { name: "Kalender & rejseplanlægning", icon: "Calendar" },
  { name: "Kontraktgennemgang", icon: "FileText" },
  { name: "Journalføring & arkivering", icon: "Archive" },
  { name: "Grafisk design", icon: "Palette" },
  { name: "Præsentationer & slides", icon: "Presentation" },
  { name: "AI-opgaver", icon: "Sparkles" },
  { name: "Hjemmeside & IT", icon: "Globe" },
  { name: "Andet", icon: "MoreHorizontal" },
];
